Feature/mooc 3076
OPI-PIB/navoica-api pull request #24
Opened 2023-02-10 13:42 UTC by nazgut

MOOC-3076 add checking if course has Power form

2023-02-10 19:23 UTC, hoffmannkrzysztof commented
1. Wrong destination branch to merge
2. Incorrect title of PR

2023-02-13 07:59 UTC, nazgut commented
Ad 1 changed
Ad 2 changed

2023-02-15 08:02 UTC, hoffmannkrzysztof commented
Brak wg zadania: 7. Adres rejestracji zdalnej

2023-03-13 10:38 UTC, hoffmannkrzysztof requested changes

2023-03-13 10:38 UTC, hoffmannkrzysztof commented on navoica_api/api/v1/views.py
> +        if course.other_course_settings.get('external_enroll') or course.other_course_settings.get('external_enroll').get('value'):
its better instead of using if: just make an assignment to variable to power = course....

2023-03-13 10:38 UTC, hoffmannkrzysztof commented on navoica_api/api/v1/views.py
> +        return Response({"power": power})
power is always False

2023-03-16 15:20 UTC, merged